  // BT2シリーズ (魂魄の冥導士) - 82枚 - 正しいデータ
  {
    id: "BT2-1",
    name: "アクアノーヴァの野良猫",
    type: "ユニット",
    cost: 3,
    bp: "5000",
    sp: undefined,
    ability: undefined,
    description: "自由になった元飼い猫は猫社会の頂点を目指して奔走する。",
    faction: "アクアノーヴァ/アニマル",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-1.png",
    color: "blue",
    rarity: "C",
    cardNumber: "BT2-1",
    colorBalance: "青1",
    colorCost: 1,
    colorlessCost: 2,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["アクアノーヴァ", "アニマル"],
    effect: undefined,
    flavorText: "自由になった元飼い猫は猫社会の頂点を目指して奔走する。"
  },
  {
    id: "BT2-2",
    name: "ピンク",
    type: "ユニット",
    cost: 4,
    bp: "5000",
    sp: undefined,
    ability: "【登場時】ターン終了まで、相手のユニット1体をコスト-1。",
    description: "ピンク色に変化したルナ。愛らしい見た目で相手を騙し、戦闘を有利に運ぶ。",
    faction: "ルナ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-2.png",
    color: "red",
    rarity: "RR",
    cardNumber: "BT2-2",
    colorBalance: "赤2",
    colorCost: 2,
    colorlessCost: 2,
    effectType: ["コスト減少"],
    pack: "魂魄の冥導士",
    traits: ["ルナ", "CNP"],
    effect: "【登場時】ターン終了まで、相手のユニット1体をコスト-1。",
    flavorText: "ピンク色に変化したルナ。愛らしい見た目で相手を騙し、戦闘を有利に運ぶ。"
  },