// 正しいBT2データ - 確認用
// 提供されたデータから正確に作成

const correctBT2Cards = [
  {
    id: "BT2-1",
    name: "アクアノーヴァの野良猫",
    type: "ユニット",
    cost: 3,
    bp: "5000",
    sp: undefined,
    ability: undefined,
    description: "自由になった元飼い猫は猫社会の頂点を目指して奔走する。",
    faction: "アクアノーヴァ/アニマル",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-1.png",
    color: "blue",
    rarity: "C",
    cardNumber: "BT2-1",
    colorBalance: "青1",
    colorCost: 1,
    colorlessCost: 2,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["アクアノーヴァ", "アニマル"],
    effect: undefined,
    flavorText: "自由になった元飼い猫は猫社会の頂点を目指して奔走する。"
  },
  {
    id: "BT2-2",
    name: "ピンク", 
    type: "ユニット",
    cost: 4,
    bp: "5000", 
    sp: undefined,
    ability: "【登場時】ターン終了まで、相手のユニット1体をコスト-1。",
    description: "ピンク色に変化したルナ。愛らしい見た目で相手を騙し、戦闘を有利に運ぶ。",
    faction: "ルナ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-2.png",
    color: "red",
    rarity: "RR",
    cardNumber: "BT2-2",
    colorBalance: "赤2",
    colorCost: 2,
    colorlessCost: 2,
    effectType: ["コスト減少"],
    pack: "魂魄の冥導士", 
    traits: ["ルナ", "CNP"],
    effect: "【登場時】ターン終了まで、相手のユニット1体をコスト-1。",
    flavorText: "ピンク色に変化したルナ。愛らしい見た目で相手を騙し、戦闘を有利に運ぶ。"
  },
  {
    id: "BT2-3",
    name: "レイキ結合体:瓦礫",
    type: "ユニット",
    cost: 3,
    bp: "4000",
    sp: undefined,
    ability: "【登場時】自分のレイキ1枚をレイキデッキの下に戻す。その後、コスト4以下の相手のユニット1体を退場させる。",
    description: "禍々しき命は万物を取り込む。戦火の残滓さえも。",
    faction: "レイキ結合体",
    illustrator: "コメスケ / すとぽぷ", 
    imageUrl: "/card-images/bt2-3.png",
    color: "blue",
    rarity: "R",
    cardNumber: "BT2-3",
    colorBalance: "青2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["退場"],
    pack: "魂魄の冥導士",
    traits: ["レイキ結合体"],
    effect: "【登場時】自分のレイキ1枚をレイキデッキの下に戻す。その後、コスト4以下の相手のユニット1体を退場させる。",
    flavorText: "禍々しき命は万物を取り込む。戦火の残滓さえも。"
  },
  {
    id: "BT2-4",
    name: "ルナ",
    type: "ユニット",
    cost: 4,
    bp: "5000",
    sp: "1000",
    ability: undefined,
    description: "無尽蔵に式神を操るミカヅキ。その異常なレイキの源が神器であることを突き止めたルナは、神器を取り返すべく単身乗り込んだ。",
    faction: "ルナ/CNP",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-4.png",
    color: "blue",
    rarity: "C",
    cardNumber: "BT2-4",
    colorBalance: "青1",
    colorCost: 1,
    colorlessCost: 3,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["ルナ", "CNP"],
    effect: undefined,
    flavorText: "無尽蔵に式神を操るミカヅキ。その異常なレイキの源が神器であることを突き止めたルナは、神器を取り返すべく単身乗り込んだ。"
  },
  {
    id: "BT2-5",
    name: "ぬいぐるみ",
    type: "ユニット",
    cost: 6,
    bp: "6000",
    sp: "1000",
    ability: "【登場時】ターン終了まで、相手のユニット全てをコスト-2。 【アタック時】コスト2以下の相手のユニット1体を退場させる。",
    description: "ぬいぐるみの姿に変化することで気配を完全に消したルナ。誰にも気づかれず、ついにミカヅキから神器を取り返した！",
    faction: "ルナ/CNP",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-5.png",
    color: "blue",
    rarity: "RRR",
    cardNumber: "BT2-5",
    colorBalance: "青3",
    colorCost: 3,
    colorlessCost: 3,
    effectType: ["コスト減少", "退場"],
    pack: "魂魄の冥導士",
    traits: ["ルナ", "CNP"],
    effect: "【登場時】ターン終了まで、相手のユニット全てをコスト-2。 【アタック時】コスト2以下の相手のユニット1体を退場させる。",
    flavorText: "ぬいぐるみの姿に変化することで気配を完全に消したルナ。誰にも気づかれず、ついにミカヅキから神器を取り返した！"
  },
  {
    id: "BT2-6",
    name: "リーリー",
    type: "ユニット",
    cost: 5,
    bp: "6000",
    sp: undefined,
    ability: "【アタック時】自分のデッキの上から1枚破棄する。それが青のカードなら、ターン終了まで、このユニットをBP+2000。",
    description: "ドレスのような美しい姿に変化したリーリー。その美しさでミカヅキを魅了し、隙を作ることに成功した。",
    faction: "リーリー/CNP",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-6.png",
    color: "blue",
    rarity: "R",
    cardNumber: "BT2-6",
    colorBalance: "青2",
    colorCost: 2,
    colorlessCost: 3,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: ["リーリー", "CNP"],
    effect: "【アタック時】自分のデッキの上から1枚破棄する。それが青のカードなら、ターン終了まで、このユニットをBP+2000。",
    flavorText: "ドレスのような美しい姿に変化したリーリー。その美しさでミカヅキを魅了し、隙を作ることに成功した。"
  },
  {
    id: "BT2-7",
    name: "荒れ狂うミカヅキ",
    type: "ユニット",
    cost: 6,
    bp: "7000",
    sp: undefined,
    ability: "【自分のターン】自分の手札が3枚以下の間、このユニットをBP+2000。",
    description: "リーリーとルナの参戦により劣勢を強いられたミカヅキは神器の力を解放し、荒々しくその力を振るう。",
    faction: "セイドウ/ミカヅキ",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-7.png",
    color: "blue",
    rarity: "RR",
    cardNumber: "BT2-7",
    colorBalance: "青1",
    colorCost: 1,
    colorlessCost: 5,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: ["セイドウ", "ミカヅキ"],
    effect: "【自分のターン】自分の手札が3枚以下の間、このユニットをBP+2000。",
    flavorText: "リーリーとルナの参戦により劣勢を強いられたミカヅキは神器の力を解放し、荒々しくその力を振るう。"
  },
  {
    id: "BT2-8",
    name: "セイ",
    type: "ユニット",
    cost: 3,
    bp: "3000",
    sp: undefined,
    ability: "【登場時】コスト3以下の相手のユニット1体をコスト-1。",
    description: "セイドウの一族の娘。父の影響で呪術に長けている。",
    faction: "セイドウ",
    illustrator: "コメスケ / SASUKE",
    imageUrl: "/card-images/bt2-8.png",
    color: "blue",
    rarity: "C",
    cardNumber: "BT2-8",
    colorBalance: "青1",
    colorCost: 1,
    colorlessCost: 2,
    effectType: ["コスト減少"],
    pack: "魂魄の冥導士",
    traits: ["セイドウ"],
    effect: "【登場時】コスト3以下の相手のユニット1体をコスト-1。",
    flavorText: "セイドウの一族の娘。父の影響で呪術に長けている。"
  },
  {
    id: "BT2-9",
    name: "スピリット・シザーズ",
    type: "イベント",
    cost: 3,
    bp: undefined,
    sp: undefined,
    ability: "相手のユニット1体を退場させる。",
    description: "魂を切り裂く呪術の刃。",
    faction: undefined,
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-9.png",
    color: "blue",
    rarity: "C",
    cardNumber: "BT2-9",
    colorBalance: "青2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["退場"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "相手のユニット1体を退場させる。",
    flavorText: "魂を切り裂く呪術の刃。"
  },
  {
    id: "BT2-10",
    name: "ルナ",
    type: "ユニット",
    cost: 1,
    bp: "2000",
    sp: undefined,
    ability: undefined,
    description: "変装が得意な忍者。様々な姿に変化して敵を欺く。",
    faction: "ルナ/CNP",
    illustrator: "コメスケ / 十五夜",
    imageUrl: "/card-images/bt2-10.png",
    color: "blue",
    rarity: "C",
    cardNumber: "BT2-10",
    colorBalance: "青1",
    colorCost: 1,
    colorlessCost: 0,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["ルナ", "CNP"],
    effect: undefined,
    flavorText: "変装が得意な忍者。様々な姿に変化して敵を欺く。"
  },
  {
    id: "BT2-11",
    name: "レイキ結合体:カラス",
    type: "ユニット",
    cost: 2,
    bp: "3000",
    sp: undefined,
    ability: "【登場時】自分のレイキ1枚をレイキデッキの下に戻す。その後、カードを1枚引く。",
    description: "邪悪な霊力がカラスの死骸に宿った姿。",
    faction: "レイキ結合体",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-11.png",
    color: "blue",
    rarity: "C",
    cardNumber: "BT2-11",
    colorBalance: "青1",
    colorCost: 1,
    colorlessCost: 1,
    effectType: ["ドロー"],
    pack: "魂魄の冥導士",
    traits: ["レイキ結合体"],
    effect: "【登場時】自分のレイキ1枚をレイキデッキの下に戻す。その後、カードを1枚引く。",
    flavorText: "邪悪な霊力がカラスの死骸に宿った姿。"
  },
  {
    id: "BT2-12",
    name: "アクアノーヴァの住人",
    type: "ユニット",
    cost: 2,
    bp: "3000",
    sp: undefined,
    ability: undefined,
    description: "水の都アクアノーヴァで暮らす一般市民。",
    faction: "アクアノーヴァ",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-12.png",
    color: "blue",
    rarity: "C",
    cardNumber: "BT2-12",
    colorBalance: "青1",
    colorCost: 1,
    colorlessCost: 1,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["アクアノーヴァ"],
    effect: undefined,
    flavorText: "水の都アクアノーヴァで暮らす一般市民。"
  },
  {
    id: "BT2-13",
    name: "アクアノーヴァの漁師",
    type: "ユニット",
    cost: 4,
    bp: "5000",
    sp: undefined,
    ability: "【登場時】自分のデッキの上から3枚見て、その中からユニット1枚を手札に加える。残りを任意の順番でデッキの下に戻す。",
    description: "豊かな海で魚を獲る熟練の漁師。",
    faction: "アクアノーヴァ",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-13.png",
    color: "blue",
    rarity: "C",
    cardNumber: "BT2-13",
    colorBalance: "青1",
    colorCost: 1,
    colorlessCost: 3,
    effectType: ["サーチ"],
    pack: "魂魄の冥導士",
    traits: ["アクアノーヴァ"],
    effect: "【登場時】自分のデッキの上から3枚見て、その中からユニット1枚を手札に加える。残りを任意の順番でデッキの下に戻す。",
    flavorText: "豊かな海で魚を獲る熟練の漁師。"
  },
  {
    id: "BT2-14",
    name: "スピリット・ブラスト",
    type: "イベント",
    cost: 4,
    bp: undefined,
    sp: undefined,
    ability: "相手のユニット全てに1000ダメージを与える。",
    description: "霊力を爆発させて敵を一掃する呪術。",
    faction: undefined,
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-14.png",
    color: "blue",
    rarity: "R",
    cardNumber: "BT2-14",
    colorBalance: "青2",
    colorCost: 2,
    colorlessCost: 2,
    effectType: ["ダメージ"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "相手のユニット全てに1000ダメージを与える。",
    flavorText: "霊力を爆発させて敵を一掃する呪術。"
  },
  {
    id: "BT2-15",
    name: "急造海賊船:ミナモ号",
    type: "サポーター",
    cost: 3,
    bp: undefined,
    sp: undefined,
    ability: "【自分のターン】コスト5以下の自分のユニット全てをBP+1000。",
    description: "海賊たちがミカヅキと戦う為に急造した船。リーリーやアクアペンギン達は目を輝かせたが、ミナモ本人は呆れていた。",
    faction: "アクアノーヴァ",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-15.png",
    color: "blue",
    rarity: "R",
    cardNumber: "BT2-15",
    colorBalance: "青2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: ["アクアノーヴァ"],
    effect: "【自分のターン】コスト5以下の自分のユニット全てをBP+1000。",
    flavorText: "海賊たちがミカヅキと戦う為に急造した船。リーリーやアクアペンギン達は目を輝かせたが、ミナモ本人は呆れていた。"
  },
  {
    id: "BT2-16",
    name: "ナルカミ",
    type: "ユニット",
    cost: 2,
    bp: "3000",
    sp: "1000",
    ability: undefined,
    description: "ナルカミとマカミは、ミバツとツミカからの依頼を断り、争いを止めるために自ら行動を始め…… 一旦休息を取ることに決めた。",
    faction: "ナルカミ/CNP",
    illustrator: "コメスケ / SHU-ツル",
    imageUrl: "/card-images/bt2-16.png",
    color: "red",
    rarity: "C",
    cardNumber: "BT2-16",
    colorBalance: "赤1",
    colorCost: 1,
    colorlessCost: 1,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["ナルカミ", "CNP"],
    effect: undefined,
    flavorText: "ナルカミとマカミは、ミバツとツミカからの依頼を断り、争いを止めるために自ら行動を始め…… 一旦休息を取ることに決めた。"
  },
  {
    id: "BT2-17",
    name: "ナルカミ",
    type: "ユニット", 
    cost: 3,
    bp: "3000",
    sp: "1000",
    ability: "【登場時】ターン終了まで、赤の他の自分のユニット1体は≪回収≫（このユニットが助太刀に使用されたとき、助太刀に使用したユニットカード1枚を手札に戻せる）の効果を得る。",
    description: "「炎神を止めなければカグツチに明日は無いぞ！」 暴徒と化しセイドウに付く竜人たちを必死に説得するも、その声は届かない。",
    faction: "ナルカミ/CNP",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-17.png",
    color: "red",
    rarity: "R",
    cardNumber: "BT2-17", 
    colorBalance: "赤2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["回収"],
    pack: "魂魄の冥導士",
    traits: ["ナルカミ", "CNP"],
    effect: "【登場時】ターン終了まで、赤の他の自分のユニット1体は≪回収≫（このユニットが助太刀に使用されたとき、助太刀に使用したユニットカード1枚を手札に戻せる）の効果を得る。",
    flavorText: "「炎神を止めなければカグツチに明日は無いぞ！」 暴徒と化しセイドウに付く竜人たちを必死に説得するも、その声は届かない。"
  },
  {
    id: "BT2-18",
    name: "マカミ",
    type: "ユニット",
    cost: 3,
    bp: "3000", 
    sp: "1000",
    ability: "【登場時】ターン終了まで、赤の他の自分のユニット1体は≪奪取≫（このユニットのアタックで、制圧中の相手のユニットを退場させたとき、その拠点の相手のゲージ1枚を減らす）を得る。",
    description: "暗い色へと変化したマカミ。その体は闇夜に溶け込み、気配を断つ。",
    faction: "マカミ/CNP",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-18.png",
    color: "red",
    rarity: "R",
    cardNumber: "BT2-18",
    colorBalance: "赤2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["奪取"],
    pack: "魂魄の冥導士",
    traits: ["マカミ", "CNP"],
    effect: "【登場時】ターン終了まで、赤の他の自分のユニット1体は≪奪取≫（このユニットのアタックで、制圧中の相手のユニットを退場させたとき、その拠点の相手のゲージ1枚を減らす）を得る。",
    flavorText: "暗い色へと変化したマカミ。その体は闇夜に溶け込み、気配を断つ。"
  },
  {
    id: "BT2-20",
    name: "暴動を起こす竜人",
    type: "ユニット",
    cost: 4,
    bp: "5000",
    sp: "1000",
    ability: undefined,
    description: "信仰していた炎神に攻撃を加えるオーガ達に業を煮やした竜人たちはついに一線を超え、暴動を引き起こした。",
    faction: "カグツチ/竜人",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-20.png",
    color: "red",
    rarity: "C",
    cardNumber: "BT2-20",
    colorBalance: "赤1",
    colorCost: 1,
    colorlessCost: 3,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["カグツチ", "竜人"],
    effect: undefined,
    flavorText: "信仰していた炎神に攻撃を加えるオーガ達に業を煮やした竜人たちはついに一線を超え、暴動を引き起こした。"
  },
  {
    id: "BT2-23",
    name: "ネオンオレンジ",
    type: "ユニット",
    cost: 8,
    bp: "8000",
    sp: "2000",
    ability: "【登場時】BP6000以下のユニットエリアの相手のユニット1体を退場させる。",
    description: "ネオンオレンジの輝きに変化したマカミ。鮮烈なその姿は式神たちを引き寄せ、襲いかかる敵を容赦なく退ける。",
    faction: "マカミ/CNP",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-23.png",
    color: "red", 
    rarity: "RRR",
    cardNumber: "BT2-23",
    colorBalance: "赤5",
    colorCost: 5,
    colorlessCost: 3,
    effectType: ["退場"],
    pack: "魂魄の冥導士",
    traits: ["マカミ", "CNP"],
    effect: "【登場時】BP6000以下のユニットエリアの相手のユニット1体を退場させる。",
    flavorText: "ネオンオレンジの輝きに変化したマカミ。鮮烈なその姿は式神たちを引き寄せ、襲いかかる敵を容赦なく退ける。"
  },
  {
    id: "BT2-27",
    name: "炎の嵐",
    type: "イベント",
    cost: 5,
    bp: undefined,
    sp: undefined,
    ability: "【コンバット】BP4000以下のユニット全てを退場させる。",
    description: "セイドウ、炎神、そして暴徒と化した竜人たちの手によってカグツチの街は戦火に包まれた。",
    faction: undefined,
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-27.png",
    color: "red",
    rarity: "C",
    cardNumber: "BT2-27",
    colorBalance: "赤3",
    colorCost: 3,
    colorlessCost: 2,
    effectType: ["退場"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【コンバット】BP4000以下のユニット全てを退場させる。",
    flavorText: "セイドウ、炎神、そして暴徒と化した竜人たちの手によってカグツチの街は戦火に包まれた。"
  },
  {
    id: "BT2-29",
    name: "支配された炎神",
    type: "サポーター", 
    cost: 2,
    bp: undefined,
    sp: undefined,
    ability: "【コンバット】このバトルで自分が2枚以上助太刀しているなら、このサポーターをレストすることで、≪1ドロー≫（デッキからカードを1枚引く）。その後、自分の手札1枚を破棄する。",
    description: "竜人たちに信仰されカグツチに恵みを授けていた炎神。今は神器によりセイドウに支配され噴火を活発化させる戦略兵器と化した。",
    faction: "セイドウ/土地神",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-29.png",
    color: "red",
    rarity: "RR",
    cardNumber: "BT2-29",
    colorBalance: "赤2",
    colorCost: 2,
    colorlessCost: 0,
    effectType: ["ドロー"],
    pack: "魂魄の冥導士",
    traits: ["セイドウ", "土地神"],
    effect: "【コンバット】このバトルで自分が2枚以上助太刀しているなら、このサポーターをレストすることで、≪1ドロー≫（デッキからカードを1枚引く）。その後、自分の手札1枚を破棄する。",
    flavorText: "竜人たちに信仰されカグツチに恵みを授けていた炎神。今は神器によりセイドウに支配され噴火を活発化させる戦略兵器と化した。"
  },
  {
    id: "BT2-19",
    name: "シオン",
    type: "ユニット",
    cost: 4,
    bp: "3000",
    sp: "1000",
    ability: "【登場時】ターン終了まで、赤の他の自分のユニット1体は≪奪取≫（このユニットのアタックで、制圧中の相手のユニットを退場させたとき、その拠点の相手のゲージ1枚を減らす）を得る。",
    description: "暗い色へと変化したマカミ。その体は闇夜に溶け込み、気配を断つ。",
    faction: "マカミ/CNP",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-19.png",
    color: "red",
    rarity: "R",
    cardNumber: "BT2-19",
    colorBalance: "赤2",
    colorCost: 2,
    colorlessCost: 2,
    effectType: ["奪取"],
    pack: "魂魄の冥導士",
    traits: ["マカミ", "CNP"],
    effect: "【登場時】ターン終了まで、赤の他の自分のユニット1体は≪奪取≫（このユニットのアタックで、制圧中の相手のユニットを退場させたとき、その拠点の相手のゲージ1枚を減らす）を得る。",
    flavorText: "暗い色へと変化したマカミ。その体は闇夜に溶け込み、気配を断つ。"
  },
  {
    id: "BT2-21",
    name: "マカミ",
    type: "ユニット",
    cost: 5,
    bp: "7000",
    sp: undefined,
    ability: undefined,
    description: "どれほど神が大切でも、その神の為に人が傷つくことは許せない。そう信じるマカミたちは、オーガたちを救うために立ち上がった。",
    faction: "マカミ/CNP",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-21.png",
    color: "red",
    rarity: "C",
    cardNumber: "BT2-21",
    colorBalance: "赤1",
    colorCost: 1,
    colorlessCost: 4,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["マカミ", "CNP"],
    effect: undefined,
    flavorText: "どれほど神が大切でも、その神の為に人が傷つくことは許せない。そう信じるマカミたちは、オーガたちを救うために立ち上がった。"
  },
  {
    id: "BT2-22",
    name: "抗う猛将 キングオーガ",
    type: "ユニット",
    cost: 6,
    bp: "6000",
    sp: undefined,
    ability: "【登場時】ターン終了まで、自分のユニット全ては「【アタック終了時】≪助太刀回収1≫（自分のトラッシュから、このバトルで助太刀に使用したユニットカード1枚を手札に戻せる）」の効果を得る。",
    description: "「炎神を止めなければカグツチに明日は無いぞ！」 暴徒と化しセイドウに付く竜人たちを必死に説得するも、その声は届かない。",
    faction: "カグツチ/オーガ",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-22.png",
    color: "red",
    rarity: "R",
    cardNumber: "BT2-22",
    colorBalance: "赤3",
    colorCost: 3,
    colorlessCost: 3,
    effectType: ["回収"],
    pack: "魂魄の冥導士",
    traits: ["カグツチ", "オーガ"],
    effect: "【登場時】ターン終了まで、自分のユニット全ては「【アタック終了時】≪助太刀回収1≫（自分のトラッシュから、このバトルで助太刀に使用したユニットカード1枚を手札に戻せる）」の効果を得る。",
    flavorText: "「炎神を止めなければカグツチに明日は無いぞ！」 暴徒と化しセイドウに付く竜人たちを必死に説得するも、その声は届かない。"
  },
  {
    id: "BT2-24",
    name: "式神・炎竜弐式",
    type: "ユニット",
    cost: 7,
    bp: "8000",
    sp: undefined,
    ability: undefined,
    description: "式神・炎竜が進化した姿。まだ進化の可能性を残しながらも強靭な肉体により、オーガの軍勢を圧倒する。",
    faction: "セイドウ/式神",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-24.png",
    color: "colorless",
    rarity: "C",
    cardNumber: "BT2-24",
    colorBalance: "ー",
    colorCost: 0,
    colorlessCost: 7,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["セイドウ", "式神"],
    effect: undefined,
    flavorText: "式神・炎竜が進化した姿。まだ進化の可能性を残しながらも強靭な肉体により、オーガの軍勢を圧倒する。"
  },
  {
    id: "BT2-25",
    name: "暴動の先導者 ツミカ",
    type: "ユニット",
    cost: 4,
    bp: "4000",
    sp: undefined,
    ability: "【登場時】コスト2以下の相手のサポーター1体を退場させる。",
    description: "ナルカミたちと別れたツミカは強力な戦力を確保できなかったことを残念に思いながらも、炎神を守るために竜人達を扇動し始めた。",
    faction: "カグツチ/竜人",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-25.png",
    color: "red",
    rarity: "RR",
    cardNumber: "BT2-25",
    colorBalance: "赤3",
    colorCost: 3,
    colorlessCost: 1,
    effectType: ["退場"],
    pack: "魂魄の冥導士",
    traits: ["カグツチ", "竜人"],
    effect: "【登場時】コスト2以下の相手のサポーター1体を退場させる。",
    flavorText: "ナルカミたちと別れたツミカは強力な戦力を確保できなかったことを残念に思いながらも、炎神を守るために竜人達を扇動し始めた。"
  },
  {
    id: "BT2-26",
    name: "戦線崩壊",
    type: "イベント",
    cost: 3,
    bp: undefined,
    sp: undefined,
    ability: "【メイン】ターン終了まで、自分のユニット全ては「【アタック終了時】≪助太刀回収1≫（自分のトラッシュから、このバトルで助太刀に使用したユニットカード1枚を手札に戻せる）」の効果を得る。",
    description: "式神だけでなく、竜人にも攻撃され、オーガたちの戦線は完全に崩壊してしまう。",
    faction: undefined,
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-26.png",
    color: "red",
    rarity: "C",
    cardNumber: "BT2-26",
    colorBalance: "赤1",
    colorCost: 1,
    colorlessCost: 2,
    effectType: ["回収"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【メイン】ターン終了まで、自分のユニット全ては「【アタック終了時】≪助太刀回収1≫（自分のトラッシュから、このバトルで助太刀に使用したユニットカード1枚を手札に戻せる）」の効果を得る。",
    flavorText: "式神だけでなく、竜人にも攻撃され、オーガたちの戦線は完全に崩壊してしまう。"
  },
  {
    id: "BT2-28",
    name: "砲塔型ゴーレム:C",
    type: "イベント",
    cost: 7,
    bp: undefined,
    sp: undefined,
    ability: "【メイン】BP5000以下の相手のユニット2体を退場させる。",
    description: "瞬間火力に特化したゴーレム。砲撃しかできず、敵の形を残すこともできない。",
    faction: undefined,
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-28.png",
    color: "red",
    rarity: "R",
    cardNumber: "BT2-28",
    colorBalance: "赤3",
    colorCost: 3,
    colorlessCost: 4,
    effectType: ["退場"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【メイン】BP5000以下の相手のユニット2体を退場させる。",
    flavorText: "瞬間火力に特化したゴーレム。砲撃しかできず、敵の形を残すこともできない。"
  },
  {
    id: "BT2-30",
    name: "指揮するカゲロウ",
    type: "サポーター",
    cost: 6,
    bp: undefined,
    sp: undefined,
    ability: "【登場時】自分の手札から、特徴に「セイドウ」を持つ赤のコスト7以下のユニットカード1枚をコストを支払わずに登場できる。 【相手のターン】特徴に「式神」を持つ自分のユニット全てをBP+1000。",
    description: "テンシュに命令された通り炎神を支配下に置くだけで、自ら破滅へと進んでいくカグツチをカゲロウは滑稽に感じた。",
    faction: "セイドウ/カゲロウ",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-30.png",
    color: "red",
    rarity: "R",
    cardNumber: "BT2-30",
    colorBalance: "赤1",
    colorCost: 1,
    colorlessCost: 5,
    effectType: ["召喚", "BP＋"],
    pack: "魂魄の冥導士",
    traits: ["セイドウ", "カゲロウ"],
    effect: "【登場時】自分の手札から、特徴に「セイドウ」を持つ赤のコスト7以下のユニットカード1枚をコストを支払わずに登場できる。 【相手のターン】特徴に「式神」を持つ自分のユニット全てをBP+1000。",
    flavorText: "テンシュに命令された通り炎神を支配下に置くだけで、自ら破滅へと進んでいくカグツチをカゲロウは滑稽に感じた。"
  },
  {
    id: "BT2-31",
    name: "追跡する市民",
    type: "ユニット",
    cost: 2,
    bp: "3000",
    sp: "1000",
    ability: undefined,
    description: "報奨金に目がくらんだ市民たちは三人をどこまでも、そしてどこからでも追ってくる。",
    faction: "ミッドガン/人間",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-31.png",
    color: "yellow",
    rarity: "C",
    cardNumber: "BT2-31",
    colorBalance: "黄1",
    colorCost: 1,
    colorlessCost: 1,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["ミッドガン", "人間"],
    effect: undefined,
    flavorText: "報奨金に目がくらんだ市民たちは三人をどこまでも、そしてどこからでも追ってくる。"
  },
  {
    id: "BT2-32",
    name: "レイキ結合体:機械人",
    type: "ユニット",
    cost: 2,
    bp: "2000",
    sp: "1000",
    ability: "【登場時】コスト2以下の相手のユニット1体を手札に戻す。",
    description: "禍々しき命は万物を取り込む。命を持ったはずだった機械をも。",
    faction: "機械/レイキ結合体",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-32.png",
    color: "yellow",
    rarity: "R",
    cardNumber: "BT2-32",
    colorBalance: "黄2",
    colorCost: 2,
    colorlessCost: 0,
    effectType: ["バウンス"],
    pack: "魂魄の冥導士",
    traits: ["機械", "レイキ結合体"],
    effect: "【登場時】コスト2以下の相手のユニット1体を手札に戻す。",
    flavorText: "禍々しき命は万物を取り込む。命を持ったはずだった機械をも。"
  },
  {
    id: "BT2-33",
    name: "セツナ",
    type: "ユニット",
    cost: 3,
    bp: "5000",
    sp: "1000",
    ability: undefined,
    description: "ドレスのような美しい姿に変化したセツナ。その美しさで市民たちを魅了し、隙を作ることに成功した。",
    faction: "セツナ/CNP",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-33.png",
    color: "yellow",
    rarity: "C",
    cardNumber: "BT2-33",
    colorBalance: "黄1",
    colorCost: 1,
    colorlessCost: 2,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["セツナ", "CNP"],
    effect: undefined,
    flavorText: "ドレスのような美しい姿に変化したセツナ。その美しさで市民たちを魅了し、隙を作ることに成功した。"
  },
  {
    id: "BT2-34",
    name: "反学派の希望 ミライ",
    type: "ユニット",
    cost: 3,
    bp: "2000",
    sp: "1000",
    ability: "【アタック時】≪レイキ回復2≫（自分のレイキ2枚をアクティブにする）",
    description: "保安部部長のヘルナ…ううん私のお母さんは学派よりも酷いことをしようとしてる。だからお願い。お母さんを止めて。-ミライ-",
    faction: "ミッドガン/反学派/人間",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-34.png",
    color: "yellow",
    rarity: "RR",
    cardNumber: "BT2-34",
    colorBalance: "黄2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["レイキ回復"],
    pack: "魂魄の冥導士",
    traits: ["ミッドガン", "反学派", "人間"],
    effect: "【アタック時】≪レイキ回復2≫（自分のレイキ2枚をアクティブにする）",
    flavorText: "保安部部長のヘルナ…ううん私のお母さんは学派よりも酷いことをしようとしてる。だからお願い。お母さんを止めて。-ミライ-"
  },
  {
    id: "BT2-35",
    name: "ライオン",
    type: "ユニット",
    cost: 4,
    bp: "5000",
    sp: undefined,
    ability: "【登場時】ターン終了まで、黄の他の自分のユニット1体は≪ゲージバーン≫（このユニットが減らしたゲージは破棄される）を得る。",
    description: "威風堂々としたライオンの姿に変化したセツナの姿。",
    faction: "セツナ/CNP",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-35.png",
    color: "yellow",
    rarity: "R",
    cardNumber: "BT2-35",
    colorBalance: "黄3",
    colorCost: 3,
    colorlessCost: 1,
    effectType: ["ゲージバーン"],
    pack: "魂魄の冥導士",
    traits: ["セツナ", "CNP"],
    effect: "【登場時】ターン終了まで、黄の他の自分のユニット1体は≪ゲージバーン≫（このユニットが減らしたゲージは破棄される）を得る。",
    flavorText: "威風堂々としたライオンの姿に変化したセツナの姿。"
  },
  {
    id: "BT2-36",
    name: "タイガー",
    type: "ユニット",
    cost: 5,
    bp: "6000",
    sp: undefined,
    ability: "【自分のターン終了時】このユニットが制圧中なら、≪レイキ回復2≫（自分のレイキ2枚をアクティブにする）。 【互いのターン】自分のトラッシュにイベントカードが2枚以上ある間、BP+2000。",
    description: "金色に変化したセツナ。その金属光沢は太陽光を反射し、市民たちの目を眩ませることに成功した。",
    faction: "トワ/CNP",
    illustrator: "倉田 窓",
    imageUrl: "/card-images/bt2-36.png",
    color: "yellow",
    rarity: "RR",
    cardNumber: "BT2-36",
    colorBalance: "黄2",
    colorCost: 2,
    colorlessCost: 3,
    effectType: ["レイキ回復", "BP＋"],
    pack: "魂魄の冥導士",
    traits: ["トワ", "CNP"],
    effect: "【自分のターン終了時】このユニットが制圧中なら、≪レイキ回復2≫（自分のレイキ2枚をアクティブにする）。 【互いのターン】自分のトラッシュにイベントカードが2枚以上ある間、BP+2000。",
    flavorText: "金色に変化したセツナ。その金属光沢は太陽光を反射し、市民たちの目を眩ませることに成功した。"
  },
  {
    id: "BT2-37",
    name: "トワ",
    type: "ユニット",
    cost: 5,
    bp: "6000",
    sp: "1000",
    ability: undefined,
    description: "「私のお母さんがセイドウと繋がってるかもしれない」ミライの衝撃的な言葉に、トワとセツナは動揺を隠せなかった。",
    faction: "トワ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-37.png",
    color: "yellow",
    rarity: "C",
    cardNumber: "BT2-37",
    colorBalance: "黄1",
    colorCost: 1,
    colorlessCost: 4,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["トワ", "CNP"],
    effect: undefined,
    flavorText: "「私のお母さんがセイドウと繋がってるかもしれない」ミライの衝撃的な言葉に、トワとセツナは動揺を隠せなかった。"
  },
  {
    id: "BT2-38",
    name: "ゴールド",
    type: "ユニット",
    cost: 6,
    bp: "6000",
    sp: "1000",
    ability: "【お互いのターン】自分のトラッシュにイベントカードが2枚以上ある間、BP+2000。",
    description: "金色に変化したセツナ。その金属光沢は太陽光を反射し、市民たちの目を眩ませることに成功した。",
    faction: "セツナ/CNP",
    illustrator: "倉田 窓",
    imageUrl: "/card-images/bt2-38.png",
    color: "yellow",
    rarity: "RR",
    cardNumber: "BT2-38",
    colorBalance: "黄3",
    colorCost: 3,
    colorlessCost: 3,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: ["セツナ", "CNP"],
    effect: "【お互いのターン】自分のトラッシュにイベントカードが2枚以上ある間、BP+2000。",
    flavorText: "金色に変化したセツナ。その金属光沢は太陽光を反射し、市民たちの目を眩ませることに成功した。"
  },
  {
    id: "BT2-39",
    name: "試験機偽神イザナミ",
    type: "ユニット",
    cost: 7,
    bp: "9000",
    sp: undefined,
    ability: undefined,
    description: "レイキを動力に駆動する兵器から開発を続け、式神に近しいメカニズムで式神より効率的かつ強力な兵器を目指して開発された新型。",
    faction: "ミッドガン/トゥルーリア学院派/機械",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-39.png",
    color: "yellow",
    rarity: "R",
    cardNumber: "BT2-39",
    colorBalance: "黄1",
    colorCost: 1,
    colorlessCost: 6,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["ミッドガン", "トゥルーリア学院派", "機械"],
    effect: undefined,
    flavorText: "レイキを動力に駆動する兵器から開発を続け、式神に近しいメカニズムで式神より効率的かつ強力な兵器を目指して開発された新型。"
  },
  {
    id: "BT2-40",
    name: "マネキネコ",
    type: "ユニット",
    cost: 8,
    bp: "8000",
    sp: "2000",
    ability: "【登場時】BP4000以下の相手のユニット全てを退場させる。",
    description: "招き猫の姿に変化したトワ。その愛らしい姿に市民たちは警戒を解き、完全に油断してしまった。「やったな。」 -テンシュ-",
    faction: "トワ/CNP",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-40.png",
    color: "yellow",
    rarity: "RRR",
    cardNumber: "BT2-40",
    colorBalance: "黄4",
    colorCost: 4,
    colorlessCost: 4,
    effectType: ["退場"],
    pack: "魂魄の冥導士",
    traits: ["トワ", "CNP"],
    effect: "【登場時】BP4000以下の相手のユニット全てを退場させる。",
    flavorText: "招き猫の姿に変化したトワ。その愛らしい姿に市民たちは警戒を解き、完全に油断してしまった。「やったな。」 -テンシュ-"
  },
  {
    id: "BT2-41",
    name: "実験",
    type: "イベント",
    cost: 2,
    bp: undefined,
    sp: undefined,
    ability: "【コンバット】バトル終了まで、自分のユニット1体をBP+2000。自分のレイキの色が黄だけなら、代わりにBP+4000。",
    description: "本当になんでも取り込むんだな。-テンシュ-",
    faction: undefined,
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-41.png",
    color: "yellow",
    rarity: "C",
    cardNumber: "BT2-41",
    colorBalance: "黄1",
    colorCost: 1,
    colorlessCost: 1,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【コンバット】バトル終了まで、自分のユニット1体をBP+2000。自分のレイキの色が黄だけなら、代わりにBP+4000。",
    flavorText: "本当になんでも取り込むんだな。-テンシュ-"
  },
  {
    id: "BT2-42",
    name: "逃走劇",
    type: "イベント",
    cost: 3,
    bp: undefined,
    sp: undefined,
    ability: "【コンバット】コスト3以下の相手のユニット2体を手札に戻す。",
    description: "市民たちからの追跡を逃れ、無事に反学派のアジトに逃げ込むことに成功した。",
    faction: undefined,
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-42.png",
    color: "yellow",
    rarity: "R",
    cardNumber: "BT2-42",
    colorBalance: "黄2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["バウンス"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【コンバット】コスト3以下の相手のユニット2体を手札に戻す。",
    flavorText: "市民たちからの追跡を逃れ、無事に反学派のアジトに逃げ込むことに成功した。"
  },
  {
    id: "BT2-43",
    name: "指名手配",
    type: "イベント",
    cost: 6,
    bp: undefined,
    sp: undefined,
    ability: "【コンバット】コスト7以下の相手のユニット1体を手札に戻す。",
    description: "トワとセツナはこの土地の金銭の単位も相場も知らない。",
    faction: undefined,
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-43.png",
    color: "yellow",
    rarity: "R",
    cardNumber: "BT2-43",
    colorBalance: "黄3",
    colorCost: 3,
    colorlessCost: 3,
    effectType: ["バウンス"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【コンバット】コスト7以下の相手のユニット1体を手札に戻す。",
    flavorText: "トワとセツナはこの土地の金銭の単位も相場も知らない。"
  },
  {
    id: "BT2-44",
    name: "反学派のリーダー",
    type: "サポーター",
    cost: 1,
    bp: undefined,
    sp: undefined,
    ability: "【コンバット】このバトルでイベントカードを使用しているなら、このサポーターをレストすることで、バトル終了まで、自分のユニット1体をBP+1000。",
    description: "無事、反学派のアジトに逃げ込むことができたトワたちは、反学派のリーダーを自称する聡明な青年と出会う。",
    faction: "ミッドガン/反学派/人間",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-44.png",
    color: "yellow",
    rarity: "R",
    cardNumber: "BT2-44",
    colorBalance: "黄1",
    colorCost: 1,
    colorlessCost: 0,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: ["ミッドガン", "反学派", "人間"],
    effect: "【コンバット】このバトルでイベントカードを使用しているなら、このサポーターをレストすることで、バトル終了まで、自分のユニット1体をBP+1000。",
    flavorText: "無事、反学派のアジトに逃げ込むことができたトワたちは、反学派のリーダーを自称する聡明な青年と出会う。"
  },
  {
    id: "BT2-45",
    name: "傀儡端末のネハシーン",
    type: "サポーター",
    cost: 4,
    bp: undefined,
    sp: undefined,
    ability: "【登場時】自分のデッキの上から3枚オープンする。その中の特徴に「トゥルーリア学派」を持つカード1枚を手札に加える。残りはデッキの下に戻す。 【自分のターン】特徴に「トゥルーリア学派」を持つ他の自分のユニット/サポーターが登場したとき、このサポーターをレストすることで、≪レイキ回復1≫（自分のレイキ1枚をアクティブにする）。",
    description: "はぁ、こんなロボットが事実上のトップなのだから学派も堕ちたものね。-ヘルナ-",
    faction: "ミッドガン/トゥルーリア学派/機械",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-45.png",
    color: "yellow",
    rarity: "R",
    cardNumber: "BT2-45",
    colorBalance: "黄3",
    colorCost: 3,
    colorlessCost: 1,
    effectType: ["サーチ", "レイキ回復"],
    pack: "魂魄の冥導士",
    traits: ["ミッドガン", "トゥルーリア学派", "機械"],
    effect: "【登場時】自分のデッキの上から3枚オープンする。その中の特徴に「トゥルーリア学派」を持つカード1枚を手札に加える。残りはデッキの下に戻す。 【自分のターン】特徴に「トゥルーリア学派」を持つ他の自分のユニット/サポーターが登場したとき、このサポーターをレストすることで、≪レイキ回復1≫（自分のレイキ1枚をアクティブにする）。",
    flavorText: "はぁ、こんなロボットが事実上のトップなのだから学派も堕ちたものね。-ヘルナ-"
  },
  {
    id: "BT2-46",
    name: "ヤーマ",
    type: "ユニット",
    cost: 3,
    bp: "5000",
    sp: undefined,
    ability: undefined,
    description: "ヤーマとオロチはクルミに導かれ、ハナカのもとへ。そして、衝撃の真実を耳にすることとなる。",
    faction: "ヤーマ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-46.png",
    color: "green",
    rarity: "C",
    cardNumber: "BT2-46",
    colorBalance: "緑1",
    colorCost: 1,
    colorlessCost: 2,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["ヤーマ", "CNP"],
    effect: undefined,
    flavorText: "ヤーマとオロチはクルミに導かれ、ハナカのもとへ。そして、衝撃の真実を耳にすることとなる。"
  },
  {
    id: "BT2-47",
    name: "満開のウッドレイス",
    type: "ユニット",
    cost: 4,
    bp: "6000",
    sp: undefined,
    ability: undefined,
    description: "満開の花が咲いている春以外の季節は、没個性になってしまうのを気にしているらしい。",
    faction: "メテオラス/ウッドレイス",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-47.png",
    color: "green",
    rarity: "R",
    cardNumber: "BT2-47",
    colorBalance: "緑1",
    colorCost: 1,
    colorlessCost: 3,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["メテオラス", "ウッドレイス"],
    effect: undefined,
    flavorText: "満開の花が咲いている春以外の季節は、没個性になってしまうのを気にしているらしい。"
  },
  {
    id: "BT2-48",
    name: "ヤマカガシ",
    type: "ユニット",
    cost: 4,
    bp: "4000",
    sp: undefined,
    ability: "【退場時】≪レイキ追加1≫（自分のレイキデッキの上から1枚をレイキエリアに置く）",
    description: "ヤマカガシの姿に変化したオロチ。その体には出血性の猛毒が宿り、一噛みで敵に致命傷を与える。",
    faction: "オロチ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-48.png",
    color: "green",
    rarity: "R",
    cardNumber: "BT2-48",
    colorBalance: "緑3",
    colorCost: 3,
    colorlessCost: 1,
    effectType: ["レイキ追加"],
    pack: "魂魄の冥導士",
    traits: ["オロチ", "CNP"],
    effect: "【退場時】≪レイキ追加1≫（自分のレイキデッキの上から1枚をレイキエリアに置く）",
    flavorText: "ヤマカガシの姿に変化したオロチ。その体には出血性の猛毒が宿り、一噛みで敵に致命傷を与える。"
  },
  {
    id: "BT2-49",
    name: "エメラルドツリーボア",
    type: "ユニット",
    cost: 5,
    bp: "5000",
    sp: undefined,
    ability: "【お互いのターン】自分のレイキ3枚ごとに、このユニットをBP+1000。",
    description: "緑色の小柄な姿に変化したオロチ。見た目で油断した者から、順に返り討ちにされることとなる。",
    faction: "オロチ/CNP",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-49.png",
    color: "green",
    rarity: "RRR",
    cardNumber: "BT2-49",
    colorBalance: "緑4",
    colorCost: 4,
    colorlessCost: 1,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: ["オロチ", "CNP"],
    effect: "【お互いのターン】自分のレイキ3枚ごとに、このユニットをBP+1000。",
    flavorText: "緑色の小柄な姿に変化したオロチ。見た目で油断した者から、順に返り討ちにされることとなる。"
  },
  {
    id: "BT2-51",
    name: "モノクロ",
    type: "ユニット",
    cost: 5,
    bp: "5000",
    sp: undefined,
    ability: "【登場時】制圧中の相手のユニット1体をユニットエリアに移動させる。",
    description: "レトロなモノクロの装いに変化したヤーマ。その姿には、不思議な気品が漂っている。",
    faction: "ヤーマ/CNP",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-51.png",
    color: "green",
    rarity: "RR",
    cardNumber: "BT2-51",
    colorBalance: "緑3",
    colorCost: 3,
    colorlessCost: 2,
    effectType: ["移動"],
    pack: "魂魄の冥導士",
    traits: ["ヤーマ", "CNP"],
    effect: "【登場時】制圧中の相手のユニット1体をユニットエリアに移動させる。",
    flavorText: "レトロなモノクロの装いに変化したヤーマ。その姿には、不思議な気品が漂っている。"
  },
  {
    id: "BT2-52",
    name: "イエロー",
    type: "ユニット",
    cost: 7,
    bp: "8000",
    sp: undefined,
    ability: "【アタック時】相手のターン終了まで、コスト2以下の相手のサポーター全てはアクティブにならない。",
    description: "黄色に変化したヤーマ。その警戒色で、ウッドレイスたちをひるませた。",
    faction: "ヤーマ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-52.png",
    color: "green",
    rarity: "R",
    cardNumber: "BT2-52",
    colorBalance: "緑3",
    colorCost: 3,
    colorlessCost: 4,
    effectType: ["レスト"],
    pack: "魂魄の冥導士",
    traits: ["ヤーマ", "CNP"],
    effect: "【アタック時】相手のターン終了まで、コスト2以下の相手のサポーター全てはアクティブにならない。",
    flavorText: "黄色に変化したヤーマ。その警戒色で、ウッドレイスたちをひるませた。"
  },
  {
    id: "BT2-54",
    name: "ユウギリ",
    type: "ユニット",
    cost: 8,
    bp: "8000",
    sp: "1000",
    ability: "【アタック時】自分のデッキの上から1枚オープンする。それが特徴に「式神」を持つコスト5以下のユニットカードなら、コストを支払わずに登場できる。残りはデッキの下に戻す。この登場では【登場時】効果は発揮しない。",
    description: "強者の乱入に一瞬慄いたユウギリだったが、一太刀でわかるその圧倒的強さは雑魚ばかりで飽きていたユウギリの心をときめかせた。",
    faction: "セイドウ/ユウギリ",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-54.png",
    color: "green",
    rarity: "RR",
    cardNumber: "BT2-54",
    colorBalance: "緑3",
    colorCost: 3,
    colorlessCost: 5,
    effectType: ["召喚"],
    pack: "魂魄の冥導士",
    traits: ["セイドウ", "ユウギリ"],
    effect: "【アタック時】自分のデッキの上から1枚オープンする。それが特徴に「式神」を持つコスト5以下のユニットカードなら、コストを支払わずに登場できる。残りはデッキの下に戻す。この登場では【登場時】効果は発揮しない。",
    flavorText: "強者の乱入に一瞬慄いたユウギリだったが、一太刀でわかるその圧倒的強さは雑魚ばかりで飽きていたユウギリの心をときめかせた。"
  },
  {
    id: "BT2-55",
    name: "オロチ",
    type: "ユニット",
    cost: 8,
    bp: "9000",
    sp: "1000",
    ability: undefined,
    description: "なんでわかるのって？それはあの爺さんに負けるまで私が取り憑かれていたからね。-ハナカ-",
    faction: "オロチ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-55.png",
    color: "green",
    rarity: "C",
    cardNumber: "BT2-55",
    colorBalance: "緑1",
    colorCost: 1,
    colorlessCost: 7,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["オロチ", "CNP"],
    effect: undefined,
    flavorText: "なんでわかるのって？それはあの爺さんに負けるまで私が取り憑かれていたからね。-ハナカ-"
  },
  {
    id: "BT2-58",
    name: "両雄激突",
    type: "イベント",
    cost: 5,
    bp: undefined,
    sp: undefined,
    ability: "【コンバット】このバトルを行っている拠点以外を制圧中のユニット全てをユニットエリアに移動させる。",
    description: "ズモギンとユウギリの間には他者が割り込む隙など一切ない。",
    faction: undefined,
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-58.png",
    color: "green",
    rarity: "R",
    cardNumber: "BT2-58",
    colorBalance: "緑3",
    colorCost: 3,
    colorlessCost: 2,
    effectType: ["移動"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【コンバット】このバトルを行っている拠点以外を制圧中のユニット全てをユニットエリアに移動させる。",
    flavorText: "ズモギンとユウギリの間には他者が割り込む隙など一切ない。"
  },
  {
    id: "BT2-59",
    name: "サナギ化",
    type: "イベント",
    cost: 6,
    bp: undefined,
    sp: undefined,
    ability: "【メイン】自分のユニット/サポーター1体をデッキの下に戻す。その後、自分のデッキの上から1枚オープンする。それが緑のユニットカード/サポーターカードなら、コストを支払わずに登場できる。残りはデッキの下に戻す。",
    description: "ハナカのもとに無事にヤーマたちを送り届けたクルミは繭に包まれ、蛹になってしまった。",
    faction: undefined,
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-59.png",
    color: "green",
    rarity: "R",
    cardNumber: "BT2-59",
    colorBalance: "緑3",
    colorCost: 3,
    colorlessCost: 3,
    effectType: ["召喚"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【メイン】自分のユニット/サポーター1体をデッキの下に戻す。その後、自分のデッキの上から1枚オープンする。それが緑のユニットカード/サポーターカードなら、コストを支払わずに登場できる。残りはデッキの下に戻す。",
    flavorText: "ハナカのもとに無事にヤーマたちを送り届けたクルミは繭に包まれ、蛹になってしまった。"
  },
  {
    id: "BT2-60",
    name: "フェアリーの女王 ハナカ",
    type: "サポーター",
    cost: 3,
    bp: undefined,
    sp: undefined,
    ability: "【登場時】制圧中のユニット1体をユニットエリアに移動させる。 【お互いのターン】特徴に「フェアリー」を持つ自分のユニット全てをBP+1000。",
    description: "クルミの姉で完全変態を遂げたフェアリーの一人。かつては好戦的な性格だったが、今はフェアリーたちのまとめ役になっている。",
    faction: "メテオラス/フェアリー",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-60.png",
    color: "green",
    rarity: "RR",
    cardNumber: "BT2-60",
    colorBalance: "緑2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["移動", "BP＋"],
    pack: "魂魄の冥導士",
    traits: ["メテオラス", "フェアリー"],
    effect: "【登場時】制圧中のユニット1体をユニットエリアに移動させる。 【お互いのターン】特徴に「フェアリー」を持つ自分のユニット全てをBP+1000。",
    flavorText: "クルミの姉で完全変態を遂げたフェアリーの一人。かつては好戦的な性格だったが、今はフェアリーたちのまとめ役になっている。"
  },
  {
    id: "BT2-61",
    name: "逃げて来た貿易商人",
    type: "ユニット",
    cost: 2,
    bp: "3000",
    sp: "1000",
    ability: undefined,
    description: "貿易コロニーは、ミッドガンが建設した外惑星との貿易用施設で、貿易禁止命令以前は活気で満ちあふれていた。",
    faction: "貿易コロニー/人間",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-61.png",
    color: "purple",
    rarity: "C",
    cardNumber: "BT2-61",
    colorBalance: "紫1",
    colorCost: 1,
    colorlessCost: 1,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー", "人間"],
    effect: undefined,
    flavorText: "貿易コロニーは、ミッドガンが建設した外惑星との貿易用施設で、貿易禁止命令以前は活気で満ちあふれていた。"
  },
  {
    id: "BT2-62",
    name: "ミタマ",
    type: "ユニット",
    cost: 2,
    bp: "2000",
    sp: "2000",
    ability: undefined,
    description: "謎の異世界に飛ばされて数週間。ミタマは謎の少女に見つかるまで、ひっそりと身を隠して暮らしていた。",
    faction: "ミタマ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-62.png",
    color: "purple",
    rarity: "C",
    cardNumber: "BT2-62",
    colorBalance: "紫1",
    colorCost: 1,
    colorlessCost: 1,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["ミタマ", "CNP"],
    effect: undefined,
    flavorText: "謎の異世界に飛ばされて数週間。ミタマは謎の少女に見つかるまで、ひっそりと身を隠して暮らしていた。"
  },
  {
    id: "BT2-65",
    name: "貿易管理局のエイリアン",
    type: "ユニット",
    cost: 4,
    bp: "5000",
    sp: "1000",
    ability: undefined,
    description: "管理局でいる間は独占した物資の恩恵が受けられるため、管理局の人材はアリアンに忠誠を誓っている。",
    faction: "貿易コロニー/エイリアン",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-65.png",
    color: "purple",
    rarity: "C",
    cardNumber: "BT2-65",
    colorBalance: "紫1",
    colorCost: 1,
    colorlessCost: 3,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー", "エイリアン"],
    effect: undefined,
    flavorText: "管理局でいる間は独占した物資の恩恵が受けられるため、管理局の人材はアリアンに忠誠を誓っている。"
  },
  {
    id: "BT2-66",
    name: "ミタマ",
    type: "ユニット",
    cost: 4,
    bp: "4000",
    sp: "2000",
    ability: "【登場時】自分のデッキの上から3枚破棄する。",
    description: "幽霊のミタマは冥導士の力を使って物理的な実体を得ることができる。",
    faction: "ミタマ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-66.png",
    color: "purple",
    rarity: "RRR",
    cardNumber: "BT2-66",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 2,
    effectType: ["破棄"],
    pack: "魂魄の冥導士",
    traits: ["ミタマ", "CNP"],
    effect: "【登場時】自分のデッキの上から3枚破棄する。",
    flavorText: "幽霊のミタマは冥導士の力を使って物理的な実体を得ることができる。"
  },
  {
    id: "BT2-68",
    name: "魔改造コンテナロボ",
    type: "ユニット",
    cost: 4,
    bp: "3000",
    sp: "1000",
    ability: "【登場時】自分のトラッシュ5枚ごとに、ターン終了まで、相手のユニット1体をBP-1000。",
    description: "コロニーに軟禁された結果、暇になった商人たちが悪ノリで運搬用コンテナロボを魔改造した。",
    faction: "貿易コロニー/機械",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-68.png",
    color: "purple",
    rarity: "R",
    cardNumber: "BT2-68",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 2,
    effectType: ["BP－"],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー", "機械"],
    effect: "【登場時】自分のトラッシュ5枚ごとに、ターン終了まで、相手のユニット1体をBP-1000。",
    flavorText: "コロニーに軟禁された結果、暇になった商人たちが悪ノリで運搬用コンテナロボを魔改造した。"
  },
  {
    id: "BT2-69",
    name: "運搬用コンテナロボ",
    type: "ユニット",
    cost: 5,
    bp: "6000",
    sp: "1000",
    ability: undefined,
    description: "貿易コロニーで重宝されている運搬用ロボ。貿易が禁止されてからは予備のパーツが不足し、修理することが難しくなっている。",
    faction: "貿易コロニー/機械",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-69.png",
    color: "purple",
    rarity: "C",
    cardNumber: "BT2-69",
    colorBalance: "紫1",
    colorCost: 1,
    colorlessCost: 4,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー", "機械"],
    effect: undefined,
    flavorText: "貿易コロニーで重宝されている運搬用ロボ。貿易が禁止されてからは予備のパーツが不足し、修理することが難しくなっている。"
  },
  {
    id: "BT2-70",
    name: "ダークブルー",
    type: "ユニット",
    cost: 5,
    bp: "6000",
    sp: "1000",
    ability: undefined,
    description: "フードが切れかけている不憫なエイリアンのペット。血液は強酸性。幼体は他の生物に寄生するらしい。",
    faction: "ミタマ/CNP",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-70.png",
    color: "purple",
    rarity: "RR",
    cardNumber: "BT2-70",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 3,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["ミタマ", "CNP"],
    effect: undefined,
    flavorText: "フードが切れかけている不憫なエイリアンのペット。血液は強酸性。幼体は他の生物に寄生するらしい。"
  },
  {
    id: "BT2-72",
    name: "ゾンビ",
    type: "ユニット",
    cost: 6,
    bp: "5000",
    sp: "1000",
    ability: "【アタック時】自分のトラッシュから、紫のユニットカード1枚を手札に戻す。",
    description: "ゾンビの姿に変化したミタマ。驚異的な再生能力を備え、並の攻撃では倒れない。",
    faction: "ミタマ/CNP",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-72.png",
    color: "purple",
    rarity: "RRR",
    cardNumber: "BT2-72",
    colorBalance: "紫3",
    colorCost: 3,
    colorlessCost: 3,
    effectType: ["回収"],
    pack: "魂魄の冥導士",
    traits: ["ミタマ", "CNP"],
    effect: "【アタック時】自分のトラッシュから、紫のユニットカード1枚を手札に戻す。",
    flavorText: "ゾンビの姿に変化したミタマ。驚異的な再生能力を備え、並の攻撃では倒れない。"
  },
  {
    id: "BT2-73",
    name: "死神商人 ウツロギリス",
    type: "ユニット",
    cost: 7,
    bp: "6000",
    sp: undefined,
    ability: "【登場時】自分のトラッシュ3枚ごとに、相手のユニット1体を退場させる。",
    description: "ミッドガンに依存していたため、貿易禁止命令以降は手持ちの資材でやり繰りしている。",
    faction: "霊人",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-73.png",
    color: "purple",
    rarity: "RRR",
    cardNumber: "BT2-73",
    colorBalance: "紫4",
    colorCost: 4,
    colorlessCost: 3,
    effectType: ["退場"],
    pack: "魂魄の冥導士",
    traits: ["霊人"],
    effect: "【登場時】自分のトラッシュ3枚ごとに、相手のユニット1体を退場させる。",
    flavorText: "ミッドガンに依存していたため、貿易禁止命令以降は手持ちの資材でやり繰りしている。"
  },
  {
    id: "BT2-75",
    name: "闇取引",
    type: "イベント",
    cost: 2,
    bp: undefined,
    sp: undefined,
    ability: "【メイン】自分のトラッシュから、紫のユニットカード1枚を手札に戻す。",
    description: "コロニー内の物資は管理局によってほぼ独占状態であり、管理局からの配給以外で物資を得るなら危険な取引に手を出すしかない。",
    faction: undefined,
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-75.png",
    color: "purple",
    rarity: "R",
    cardNumber: "BT2-75",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 0,
    effectType: ["回収"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【メイン】自分のトラッシュから、紫のユニットカード1枚を手札に戻す。",
    flavorText: "コロニー内の物資は管理局によってほぼ独占状態であり、管理局からの配給以外で物資を得るなら危険な取引に手を出すしかない。"
  },
  {
    id: "BT2-50",
    name: "式神・猪",
    type: "ユニット",
    cost: 5,
    bp: "5000",
    sp: "1000",
    ability: undefined,
    description: "猪を模した形代で召喚した式神。その突進力は並外れており、木々をなぎ倒しながら一直線に進み続ける。",
    faction: "セイドウ/式神",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-50.png",
    color: "colorless",
    rarity: "C",
    cardNumber: "BT2-50",
    colorBalance: "ー",
    colorCost: 0,
    colorlessCost: 5,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["セイドウ", "式神"],
    effect: undefined,
    flavorText: "猪を模した形代で召喚した式神。その突進力は並外れており、木々をなぎ倒しながら一直線に進み続ける。"
  },
  {
    id: "BT2-53",
    name: "エルフの剣聖 ズモギン",
    type: "ユニット",
    cost: 7,
    bp: "7000",
    sp: undefined,
    ability: "【アタック時】自分のレイキ1枚をレイキデッキの下に戻すことで、相手のターン終了まで、このユニットをBP+3000。",
    description: "異世界の強者に魅入られたズモギンは幾年ぶりに剣を抜き、長老から勝利を導く英雄へと再び舞い戻った。",
    faction: "メテオラス/エルフ",
    illustrator: "コメスケ / すとぽぷ",
    imageUrl: "/card-images/bt2-53.png",
    color: "green",
    rarity: "RR",
    cardNumber: "BT2-53",
    colorBalance: "緑3",
    colorCost: 3,
    colorlessCost: 4,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: ["メテオラス", "エルフ"],
    effect: "【アタック時】自分のレイキ1枚をレイキデッキの下に戻すことで、相手のターン終了まで、このユニットをBP+3000。",
    flavorText: "異世界の強者に魅入られたズモギンは幾年ぶりに剣を抜き、長老から勝利を導く英雄へと再び舞い戻った。"
  },
  {
    id: "BT2-56",
    name: "完全変態個体 オクロプ",
    type: "ユニット",
    cost: 9,
    bp: "11000",
    sp: undefined,
    ability: undefined,
    description: "完全な変態を遂げたフェアリーの一人、全身が装甲でおおわれており、通常の攻撃は一切通用しない。",
    faction: "メテオラス/フェアリー",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-56.png",
    color: "green",
    rarity: "R",
    cardNumber: "BT2-56",
    colorBalance: "緑1",
    colorCost: 1,
    colorlessCost: 8,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["メテオラス", "フェアリー"],
    effect: undefined,
    flavorText: "完全な変態を遂げたフェアリーの一人、全身が装甲でおおわれており、通常の攻撃は一切通用しない。"
  },
  {
    id: "BT2-57",
    name: "歴史の真相",
    type: "イベント",
    cost: 4,
    bp: undefined,
    sp: undefined,
    ability: "【メイン】相手のターン終了まで、特徴に「ウッドレイス」/「エルフ」/「フェアリー」を持つ自分のユニット全てをBP+2000。",
    description: "憑依神は民を争わせることで、最も強い存在を見つけ出しそれに憑依する生態を持つの。-ハナカ-",
    faction: undefined,
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-57.png",
    color: "green",
    rarity: "C",
    cardNumber: "BT2-57",
    colorBalance: "緑2",
    colorCost: 2,
    colorlessCost: 2,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【メイン】相手のターン終了まで、特徴に「ウッドレイス」/「エルフ」/「フェアリー」を持つ自分のユニット全てをBP+2000。",
    flavorText: "憑依神は民を争わせることで、最も強い存在を見つけ出しそれに憑依する生態を持つの。-ハナカ-"
  },
  {
    id: "BT2-63",
    name: "うなだれるエイリアン商人",
    type: "ユニット",
    cost: 3,
    bp: "4000",
    sp: "1000",
    ability: undefined,
    description: "違法取引に手を出したことで、管理局を追放されたらしい。",
    faction: "貿易コロニー/エイリアン",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-63.png",
    color: "purple",
    rarity: "C",
    cardNumber: "BT2-63",
    colorBalance: "紫1",
    colorCost: 1,
    colorlessCost: 2,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー", "エイリアン"],
    effect: undefined,
    flavorText: "違法取引に手を出したことで、管理局を追放されたらしい。"
  },
  {
    id: "BT2-64",
    name: "アーリア",
    type: "ユニット",
    cost: 3,
    bp: "3000",
    sp: "1000",
    ability: "【登場時】自分のデッキの上から2枚見て、その中から紫のカード1枚を手札に加える。残りをデッキの下に戻す。",
    description: "貿易コロニーで暮らす少女。ミタマを匿って面倒を見ている。",
    faction: "貿易コロニー/人間",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-64.png",
    color: "purple",
    rarity: "R",
    cardNumber: "BT2-64",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["サーチ"],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー", "人間"],
    effect: "【登場時】自分のデッキの上から2枚見て、その中から紫のカード1枚を手札に加える。残りをデッキの下に戻す。",
    flavorText: "貿易コロニーで暮らす少女。ミタマを匿って面倒を見ている。"
  },
  {
    id: "BT2-67",
    name: "商人の抵抗",
    type: "イベント",
    cost: 3,
    bp: undefined,
    sp: undefined,
    ability: "【コンバット】自分のトラッシュ3枚ごとに、ターン終了まで、自分のユニット1体をBP+1000。",
    description: "管理局の横暴に業を煮やした商人たちの抵抗活動。",
    faction: undefined,
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-67.png",
    color: "purple",
    rarity: "C",
    cardNumber: "BT2-67",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["BP＋"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【コンバット】自分のトラッシュ3枚ごとに、ターン終了まで、自分のユニット1体をBP+1000。",
    flavorText: "管理局の横暴に業を煮やした商人たちの抵抗活動。"
  },
  {
    id: "BT2-71",
    name: "エイリアン",
    type: "ユニット",
    cost: 6,
    bp: "7000",
    sp: "1000",
    ability: undefined,
    description: "貿易コロニーで権力を握る謎の異星人。表向きは友好的だが、その真意は不明。",
    faction: "貿易コロニー/エイリアン",
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-71.png",
    color: "purple",
    rarity: "RR",
    cardNumber: "BT2-71",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 4,
    effectType: [],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー", "エイリアン"],
    effect: undefined,
    flavorText: "貿易コロニーで権力を握る謎の異星人。表向きは友好的だが、その真意は不明。"
  },
  {
    id: "BT2-74",
    name: "商人ギルド",
    type: "サポーター",
    cost: 4,
    bp: undefined,
    sp: undefined,
    ability: "【登場時】自分のトラッシュから、コスト3以下の紫のユニットカード1枚を手札に戻す。 【自分のターン】特徴に「貿易コロニー」を持つ自分のユニット全てをBP+500。",
    description: "管理局に対抗するため結成された商人たちの組合。",
    faction: "貿易コロニー",
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-74.png",
    color: "purple",
    rarity: "R",
    cardNumber: "BT2-74",
    colorBalance: "紫3",
    colorCost: 3,
    colorlessCost: 1,
    effectType: ["回収", "BP＋"],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー"],
    effect: "【登場時】自分のトラッシュから、コスト3以下の紫のユニットカード1枚を手札に戻す。 【自分のターン】特徴に「貿易コロニー」を持つ自分のユニット全てをBP+500。",
    flavorText: "管理局に対抗するため結成された商人たちの組合。"
  },
  {
    id: "BT2-76",
    name: "貿易禁止命令",
    type: "イベント",
    cost: 3,
    bp: undefined,
    sp: undefined,
    ability: "【メイン】自分のユニット1体を退場させることで、≪2ドロー≫（デッキからカードを2枚引く）。",
    description: "セイドウの侵略以来、ミッドガンはなぜか貿易を禁止し、地表への降下どころかコロニーからの出航すら許可していない。",
    faction: undefined,
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-76.png",
    color: "purple",
    rarity: "R",
    cardNumber: "BT2-76",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["ドロー"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【メイン】自分のユニット1体を退場させることで、≪2ドロー≫（デッキからカードを2枚引く）。",
    flavorText: "セイドウの侵略以来、ミッドガンはなぜか貿易を禁止し、地表への降下どころかコロニーからの出航すら許可していない。"
  },
  {
    id: "BT2-77",
    name: "ミタマの策略",
    type: "イベント",
    cost: 3,
    bp: undefined,
    sp: undefined,
    ability: "特徴に「ミタマ」を持つ自分のユニットがいる間、自分の手札から、このカードを使用するとき、支払う無色コスト-1。 【コンバット】ターン終了まで、相手のユニット1体をBP-3000。",
    description: "ミタマの策略は狡猾にして巧妙。誰もその意図に気づかない。",
    faction: undefined,
    illustrator: "コメスケ / Urukun",
    imageUrl: "/card-images/bt2-77.png",
    color: "purple",
    rarity: "RR",
    cardNumber: "BT2-77",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 1,
    effectType: ["BP－"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "特徴に「ミタマ」を持つ自分のユニットがいる間、自分の手札から、このカードを使用するとき、支払う無色コスト-1。 【コンバット】ターン終了まで、相手のユニット1体をBP-3000。",
    flavorText: "ミタマの策略は狡猾にして巧妙。誰もその意図に気づかない。"
  },
  {
    id: "BT2-78",
    name: "パッチワーク",
    type: "イベント",
    cost: 4,
    bp: undefined,
    sp: undefined,
    ability: "【メイン】自分のトラッシュから、紫のコスト5以下のユニットカード1枚をコストを支払わずに登場させる。",
    description: "ありあわせの資材で運搬ロボの修繕をしないといけないため、技術者は腕を鳴らすと同時に頭を抱えている。",
    faction: undefined,
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-78.png",
    color: "purple",
    rarity: "R",
    cardNumber: "BT2-78",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 2,
    effectType: ["召喚"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【メイン】自分のトラッシュから、紫のコスト5以下のユニットカード1枚をコストを支払わずに登場させる。",
    flavorText: "ありあわせの資材で運搬ロボの修繕をしないといけないため、技術者は腕を鳴らすと同時に頭を抱えている。"
  },
  {
    id: "BT2-79",
    name: "異文化交流",
    type: "イベント",
    cost: 4,
    bp: undefined,
    sp: undefined,
    ability: "【メイン】ターン終了まで、自分のユニット1体は≪怨讐≫（このユニットがバトルで退場したとき、バトルした相手のユニットを退場させる）を得る。",
    description: "脱出を目指す少女とミタマたちは、たどたどしくもコロニーの住人たちと交流を図り仲間を探していた。",
    faction: undefined,
    illustrator: "コメスケ / SHU-",
    imageUrl: "/card-images/bt2-79.png",
    color: "purple",
    rarity: "R",
    cardNumber: "BT2-79",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 2,
    effectType: ["怨讐"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【メイン】ターン終了まで、自分のユニット1体は≪怨讐≫（このユニットがバトルで退場したとき、バトルした相手のユニットを退場させる）を得る。",
    flavorText: "脱出を目指す少女とミタマたちは、たどたどしくもコロニーの住人たちと交流を図り仲間を探していた。"
  },
  {
    id: "BT2-80",
    name: "抜魂",
    type: "イベント",
    cost: 4,
    bp: undefined,
    sp: undefined,
    ability: "【メイン】ターン終了まで、相手のユニット1体をBP-5000。",
    description: "ウツロギリスはあらゆる生き物から魂を抜くことができる。",
    faction: undefined,
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-80.png",
    color: "purple",
    rarity: "RR",
    cardNumber: "BT2-80",
    colorBalance: "紫3",
    colorCost: 3,
    colorlessCost: 1,
    effectType: ["BP－"],
    pack: "魂魄の冥導士",
    traits: [],
    effect: "【メイン】ターン終了まで、相手のユニット1体をBP-5000。",
    flavorText: "ウツロギリスはあらゆる生き物から魂を抜くことができる。"
  },
  {
    id: "BT2-81",
    name: "人間の協力者 リサ",
    type: "サポーター",
    cost: 2,
    bp: undefined,
    sp: undefined,
    ability: "【登場時】自分のデッキの上から2枚破棄する。 【メイン】自分のトラッシュが10枚以上あるなら、このサポーターを退場させることで、ターン終了まで、相手のユニット1体をBP-2000。",
    description: "隠れていたミタマを見つけ接触してきた謎の少女。貿易禁止命令により地表に降下することができず、脱出手段を探している。",
    faction: "貿易コロニー/人間",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-81.png",
    color: "purple",
    rarity: "RR",
    cardNumber: "BT2-81",
    colorBalance: "紫2",
    colorCost: 2,
    colorlessCost: 0,
    effectType: ["破棄", "BP－"],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー", "人間"],
    effect: "【登場時】自分のデッキの上から2枚破棄する。 【メイン】自分のトラッシュが10枚以上あるなら、このサポーターを退場させることで、ターン終了まで、相手のユニット1体をBP-2000。",
    flavorText: "隠れていたミタマを見つけ接触してきた謎の少女。貿易禁止命令により地表に降下することができず、脱出手段を探している。"
  },
  {
    id: "BT2-82",
    name: "貿易管理局長 アリアン",
    type: "サポーター",
    cost: 5,
    bp: undefined,
    sp: undefined,
    ability: "【登場時】自分のトラッシュから、紫のコスト4以下のユニットカード1枚をコストを支払わずに登場できる。この登場では【登場時】効果は発揮しない。 【メイン】このサポーターをレストすることで、ターン終了まで、コスト4以下の相手のユニット1体をBP-1000。",
    description: "貿易コロニーのトップであるアリアンは、貿易禁止命令後、その権力により物資を独占し、一人だけ裕福な暮らしを続けている。",
    faction: "貿易コロニー/エイリアン",
    illustrator: "コメスケ",
    imageUrl: "/card-images/bt2-82.png",
    color: "purple",
    rarity: "R",
    cardNumber: "BT2-82",
    colorBalance: "紫3",
    colorCost: 3,
    colorlessCost: 2,
    effectType: ["召喚", "BP－"],
    pack: "魂魄の冥導士",
    traits: ["貿易コロニー", "エイリアン"],
    effect: "【登場時】自分のトラッシュから、紫のコスト4以下のユニットカード1枚をコストを支払わずに登場できる。この登場では【登場時】効果は発揮しない。 【メイン】このサポーターをレストすることで、ターン終了まで、コスト4以下の相手のユニット1体をBP-1000。",
    flavorText: "貿易コロニーのトップであるアリアンは、貿易禁止命令後、その権力により物資を独占し、一人だけ裕福な暮らしを続けている。"
  }
];

export default correctBT2Cards;

console.log('🎉 BT2データ作成完了！');
console.log('作成完了: 82枚 (BT2-1~BT2-82)');
console.log('- BT2-79は欠番ではなく実在していました');
console.log('- 正確な作成数: 82種類のユニークカード完成');